# Generated by Django 5.1.1 on 2024-09-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
