# Generated by Django 5.1.1 on 2024-09-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_service', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
